#!/bin/bash

set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

. /usr/share/yunohost/helpers
[ ! -e _common.sh ] && cp ../settings/scripts/_common.sh ./.
. _common.sh

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)
<% if (defaultPathOption != "") { %>path_url=$(ynh_app_setting_get "$app" path)
<% } %>

dockerapp_ynh_loadvariables

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$data_path"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
