#!/bin/bash

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
<% if (defaultPathOption != "") { %>path_url=$YNH_APP_ARG_PATH
<% } %><% if (secureAccessOption) { %>is_public=$YNH_APP_ARG_IS_PUBLIC
<% } %><% if (adminUserOption) { %>admin=$YNH_APP_ARG_ADMIN
<% } %>

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Source YunoHost helpers
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

# store settings
<% if (secureAccessOption) { %>ynh_app_setting_set $app is_public $is_public
<% } %><% if (adminUserOption) { %>ynh_app_setting_set $app admin $admin
<% } %>

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

# Check or install docker
dockerapp_ynh_checkinstalldocker

# Check domain/path availability
dockerapp_ynh_loadvariables
ynh_webpath_available $domain $path_url
ynh_webpath_register $app $domain $path_url

#=================================================
# MODIFY A CONFIG FILE
#=================================================

dockerapp_ynh_findreplaceallvaribles

#=================================================
# COPY CONF
#=================================================

# Copy files to the right place
dockerapp_ynh_copyconf

#=================================================
# START AND CREATE SERVICE
#=================================================

# docker run
dockerapp_ynh_run

# get and save port
dockerapp_ynh_getandsaveport

#=================================================
# NGINX CONFIGURATION
#=================================================

# Modify Nginx configuration file and copy it to Nginx conf directory
dockerapp_ynh_preparenginx

#=================================================
# SETUP SSOWAT
#=================================================

<% if (secureAccessOption) { %>
# Make app public if necessary or protect it
if [ $is_public -eq 1 ]
then
    ynh_app_setting_set $app skipped_uris "/"
fi
<% } else { %>
<% if (forceSecureAccess) { %><% } else { %>ynh_app_setting_set $app skipped_uris "/"<% } %>
<% } %>

#=================================================
# RELOAD SSOWAT
#=================================================

# Regenerate SSOwat conf
dockerapp_ynh_reloadservices
