#!/bin/bash

set -u

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Source YunoHost helpers
. /usr/share/yunohost/helpers
. _common.sh

#=================================================
# LOAD SETTINGS
#=================================================

# Retrieve app settings
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)

dockerapp_ynh_loadvariables

#=================================================
# STOP AND REMOVE SERVICE
#=================================================

# docker rm
dockerapp_ynh_rm

#=================================================
# REMOVE APP MAIN DIR
#=================================================

# Remove conf and app
ynh_secure_remove $data_path

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

ynh_remove_nginx_config

#=================================================
# RELOAD SSOWAT
#=================================================

# Regenerate SSOwat conf
dockerapp_ynh_reloadservices
