#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Source YunoHost helpers
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

# Retrieve app settings
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)
<% if (defaultPathOption != "") { %>path_url=$(ynh_app_setting_get "$app" path)
<% } %><% if (secureAccessOption) { %>is_public=$(ynh_app_setting_get "$app" is_public)
<% } %><% if (adminUserOption) { %>admin=$(ynh_app_setting_get "$app" admin)
<% } %>

dockerapp_ynh_loadvariables

#=================================================
# MODIFY A CONFIG FILE
#=================================================

dockerapp_ynh_findreplaceallvaribles
<% if (scriptsLoadSave) { %>
#=================================================
# BACKUP DATA IN CONTAINER
#=================================================

dockerapp_ynh_save
<% } %>
#=================================================
# STOP AND REMOVE SERVICE
#=================================================

# docker rm
dockerapp_ynh_rm

#=================================================
# START AND CREATE SERVICE
#=================================================

# docker run
dockerapp_ynh_run
<% if (scriptsLoadSave) { %>
#=================================================
# RESTORE DATA IN CONTAINER
#=================================================

dockerapp_ynh_load
<% } %>

#=================================================
# NGINX CONFIGURATION
#=================================================

# Modify Nginx configuration file and copy it to Nginx conf directory
dockerapp_ynh_preparenginx

#=================================================
# SETUP SSOWAT
#=================================================

<% if (secureAccessOption) { %>
# Make app public if necessary or protect it
if [ $is_public -eq 1 ]
then
    ynh_app_setting_set $app skipped_uris "/"
else
    ynh_app_setting_set $app protected_uris "/"
fi
<% } %>

#=================================================
# RELOAD SSOWAT
#=================================================

# Regenerate SSOwat conf
dockerapp_ynh_reloadservices
