#!/bin/bash

set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
. /usr/share/yunohost/helpers
. _common
ynh_abort_if_errors

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
<% if (defaultPathOption != "") { %>path=$(ynh_app_setting_get "$app" path)
<% } %><% if (secureAccessOption) { %>is_public=$(ynh_app_setting_get "$app" is_public)
<% } %><% if (adminUserOption) { %>admin=$(ynh_app_setting_get "$app" admin)
<% } %>

dockerapp_ynh_loadvariables
dockerapp_ynh_findreplaceallvaribles

# docker rm
dockerapp_ynh_rm

# docker run
dockerapp_ynh_run

# Modify Nginx configuration file and copy it to Nginx conf directory
dockerapp_ynh_preparenginx

<% if (secureAccessOption) { %>
# Make app public if necessary or protect it
if [ $is_public -eq 1 ]
then
    ynh_app_setting_set $app skipped_uris "/"
else
    ynh_app_setting_set $app protected_uris "/"
fi
<% } %>

# Reload Nginx and regenerate SSOwat conf
dockerapp_ynh_reloadservices
